repos:
  - repo: local
    hooks:
      - id: forbid-secrets
        name: Forbid Secrets and .env
        entry: python scripts/forbid_secrets.py
        language: system
        pass_filenames: true
        types: [text]
        exclude: '(^README.*|.*\\.md$|.*\\.MD$|.*\\.markdown$|.*\\.rst$|.*\\.txt$|^\\.env\\.example$|^instrucoes\\.md$)'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: detect-private-key
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace