-- ===============================
-- ARTIGOS DE EXEMPLO - TECHNEWS
-- ===============================

-- Inserindo artigos de exemplo para demonstração
INSERT INTO news_articles (title, description, content, url, source_domain, author, category, status, published, published_at, created_at, updated_at) VALUES
('Revolução da Inteligência Artificial em 2024', 
 'As principais tendências e avanços em IA que estão moldando o futuro da tecnologia', 
 'A inteligência artificial continua a evoluir rapidamente, com novos modelos de linguagem e aplicações práticas surgindo constantemente. Este artigo explora as principais tendências para 2024.',
 'https://techcrunch.com/ai-revolution-2024', 
 'techcrunch.com', 
 'João Silva', 
 'Inteligência Artificial', 
 'PUBLISHED', 
 true, 
 CURRENT_TIMESTAMP, 
 CURRENT_TIMESTAMP, 
 CURRENT_TIMESTAMP),

('Novas Linguagens de Programação Ganham Destaque', 
 'Rust, Go e outras linguagens modernas estão transformando o desenvolvimento de software', 
 'O cenário de desenvolvimento está em constante evolução, com novas linguagens oferecendo melhor performance, segurança e produtividade para os desenvolvedores.',
 'https://arstechnica.com/programming-languages-2024', 
 'arstechnica.com', 
 'Maria Santos', 
 'Desenvolvimento', 
 'PUBLISHED', 
 true, 
 CURRENT_TIMESTAMP, 
 CURRENT_TIMESTAMP, 
 CURRENT_TIMESTAMP),

('Cibersegurança: Principais Ameaças de 2024', 
 'Análise das vulnerabilidades mais críticas e como se proteger contra ataques modernos', 
 'Com o aumento dos ataques cibernéticos, é essencial entender as principais ameaças e implementar medidas de proteção adequadas.',
 'https://wired.com/cybersecurity-threats-2024', 
 'wired.com', 
 'Carlos Oliveira', 
 'Cibersegurança', 
 'PUBLISHED', 
 true, 
 CURRENT_TIMESTAMP, 
 CURRENT_TIMESTAMP, 
 CURRENT_TIMESTAMP),

('Startups Brasileiras Recebem Investimento Record', 
 'Ecossistema de inovação nacional atrai bilhões em investimentos estrangeiros', 
 'O Brasil está se consolidando como um hub de inovação, com startups locais recebendo aportes significativos de investidores internacionais.',
 'https://venturebeat.com/brazilian-startups-investment', 
 'venturebeat.com', 
 'Ana Costa', 
 'Startups', 
 'PUBLISHED', 
 true, 
 CURRENT_TIMESTAMP, 
 CURRENT_TIMESTAMP, 
 CURRENT_TIMESTAMP),

('Novos Processadores Prometem Revolução em Performance', 
 'Chips de nova geração oferecem ganhos significativos em eficiência energética', 
 'A indústria de semicondutores continua inovando, com novos processadores que prometem transformar a computação moderna.',
 'https://engadget.com/new-processors-2024', 
 'engadget.com', 
 'Pedro Lima', 
 'Hardware', 
 'PUBLISHED', 
 true, 
 CURRENT_TIMESTAMP, 
 CURRENT_TIMESTAMP, 
 CURRENT_TIMESTAMP);